# Set locale
export LC_CTYPE=sv_SE.UTF-8

# Git (Bash completion)
[ -f /usr/local/etc/bash_completion.d/git-completion.bash ] && . /usr/local/etc/bash_completion.d/git-completion.bash

# Prompt
# $(__git_ps1)
export PS1='\u@\h:$(basename "$(pwd)")$(__git_ps1)\$ '

# Ignore duplicate bash histories
export HISTCONTROL=ignoreboth

# Modify PATH for Homebrew
export PATH=~/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/bin:/sbin:/usr/X10/bin

# MVIM
export EDITOR='mvim -f'

# Hub is le github
alias b='bundle exec'
alias irb='pry'
alias git='hub'
alias lf='ls -laF'

# RVM!
[[ -s "/Users/Kim/.rvm/scripts/rvm" ]] && source "/Users/Kim/.rvm/scripts/rvm"
