# Set locale
export LC_CTYPE=sv_SE.UTF-8

# Git (Bash completion)
[ -f /usr/local/etc/bash_completion.d/git-completion.bash ] && . /usr/local/etc/bash_completion.d/git-completion.bash

# Prompt
# $(__git_ps1)
export PS1='\u@\h:$(basename "$(pwd)")$(__git_ps1)\$ '

# Ignore duplicate bash histories
export HISTCONTROL=ignoreboth

# Modify PATH for Homebrew
export PATH=~/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/bin:/sbin:/usr/X11/bin

# Modify NODE_PATH for rpm
export NODE_PATH=/usr/local/lib/node_modules

# MVIM
export EDITOR='vi'

# Hub is le github
alias b='bundle exec'
alias irb='pry'
alias git='hub'
alias ll='ls -laF'
alias gp='git push'
alias gl='git pull'
alias gs='git s'

# Function to change directory to a Project
function p { cd ~/Projects/$1; }
complete -C ~/.bash_completion/project.sh -o default p

# Define Vim wrappers which unsets GEM_HOME and GEM_PATH before
# invoking vim and all known aliases
#
# @author Wael Nasreddine <wael.nasreddine@gmail.com>
function define_vim_wrappers()
{
  vim_commands=(
    eview evim gview gvim gvimdiff gvimtutor rgview
    rgvim rview rvim vim vimdiff vimtutor xxd mvim
  )

  for cmd in ${vim_commands[@]}; do
    cmd_path=`/usr/bin/env which -a "${cmd}" 2>/dev/null | grep '^/'`
    if [ -x "${cmd_path}" ]; then
      eval "function ${cmd} () { (unset GEM_HOME; unset GEM_PATH; $cmd_path \$@) }"
    fi
  done
}

# RVM!
[[ -s "/Users/Kim/.rvm/scripts/rvm" ]] && source "/Users/Kim/.rvm/scripts/rvm"
