set background=dark
colorscheme solarized
set guifont=Monaco:h14

" Disable toolbar on startup
set guioptions-=T

" fullscreen maximizes vertically AND horizontally
set fuoptions=maxvert,maxhorz

" Disable bell.
set vb t_vb=
